//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TartugaLeksikovIzrancev.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderProduct = new HashSet<OrderProduct>();
        }
    
        public int IDOrder { get; set; }
        public System.DateTime OrderTime { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public int IDEmployee { get; set; }
        public int IDRestourantTable { get; set; }
        public bool IsCashless { get; set; }
        public Nullable<int> IDPromocode { get; set; }
        public int IDStatus { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Promocode Promocode { get; set; }
        public virtual RestourantTable RestourantTable { get; set; }
        public virtual Status Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProduct { get; set; }
    }
}
